#!/bin/bash
# =============================================================================
# deploy.sh — $HATE Solana SPL Token-2022 deployment
# =============================================================================
#
# Usage:
#   bash deploy.sh devnet           # safe rehearsal
#   bash deploy.sh mainnet          # real deploy, real money
#
# What this does:
#   1. Verifies tooling (solana, spl-token) is installed
#   2. Sets RPC to chosen network
#   3. Creates/loads deploy keypair (~/hate-<network>.json)
#   4. Verifies balance is sufficient (~0.3 SOL minimum)
#   5. Creates Token-2022 mint, 9 decimals
#   6. Creates treasury token account
#   7. Mints 1,000,000,000 HATE to treasury
#   8. Initializes Metaplex metadata
#   9. Saves all addresses to ~/.hate-deploy-<network>.env
#
# What this does NOT do (manual final steps, on purpose):
#   - Renounce mint authority (last action — see step 11 in LAUNCH_PLAYBOOK.md)
#   - Transfer team allocation to multisig (set up Squads first)
#   - Create Meteora DLMM pool (UI-driven, walks you through)
#
# Idempotent: re-running picks up where you left off via state file.
# =============================================================================

set -e
set -u
set -o pipefail

# ---- Parse args ----
NETWORK="${1:-}"
if [ "$NETWORK" != "devnet" ] && [ "$NETWORK" != "mainnet" ]; then
  echo "Usage: bash deploy.sh devnet|mainnet"
  exit 1
fi

# ---- Config ----
KEYPAIR="$HOME/hate-${NETWORK}.json"
STATE_FILE="$HOME/.hate-deploy-${NETWORK}.env"
TOKEN_2022_PROGRAM="TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
DECIMALS=9
TOTAL_SUPPLY=1000000000

if [ "$NETWORK" = "devnet" ]; then
  RPC="https://api.devnet.solana.com"
  MIN_BALANCE_SOL="1.5"     # devnet airdrop covers easily
else
  RPC="https://api.mainnet-beta.solana.com"
  MIN_BALANCE_SOL="0.3"     # real cost ~0.05 SOL plus rent buffer
fi

# ---- Colors ----
R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[1;34m'; X='\033[0m'

say()  { echo -e "${B}▸${X} $*"; }
ok()   { echo -e "${G}✓${X} $*"; }
warn() { echo -e "${Y}!${X} $*"; }
die()  { echo -e "${R}✗${X} $*"; exit 1; }

# ---- Verify tooling ----
say "Checking tools..."
command -v solana >/dev/null   || die "solana CLI not installed. See LAUNCH_PLAYBOOK.md Phase 1."
command -v spl-token >/dev/null|| die "spl-token CLI not installed. Run: cargo install spl-token-cli"
ok "solana $(solana --version | awk '{print $2}')"
ok "spl-token $(spl-token --version | head -1)"

# ---- State file (resume support) ----
[ -f "$STATE_FILE" ] && source "$STATE_FILE"

save_state() {
  cat > "$STATE_FILE" <<EOF
# Generated by deploy.sh — DO NOT EDIT BY HAND
# Re-run deploy.sh to resume.
NETWORK=$NETWORK
KEYPAIR=$KEYPAIR
DEPLOY_PUBKEY=${DEPLOY_PUBKEY:-}
MINT=${MINT:-}
TREASURY=${TREASURY:-}
METADATA_DONE=${METADATA_DONE:-no}
EOF
  ok "Saved state to $STATE_FILE"
}

# ---- Set RPC ----
say "Setting RPC to $NETWORK ($RPC)"
solana config set --url "$RPC" >/dev/null
ok "RPC set"

# ---- Keypair ----
if [ -f "$KEYPAIR" ]; then
  ok "Using existing keypair: $KEYPAIR"
else
  say "Generating new keypair at $KEYPAIR"
  warn "WRITE DOWN THE SEED PHRASE THAT FOLLOWS. SCREENSHOT IT. STORE IT OFFLINE."
  warn "If you lose this, you lose the deploy wallet and any funds in it."
  read -p "Press enter to continue..." _
  solana-keygen new --outfile "$KEYPAIR" --no-bip39-passphrase
fi

solana config set --keypair "$KEYPAIR" >/dev/null
DEPLOY_PUBKEY=$(solana-keygen pubkey "$KEYPAIR")
ok "Deploy pubkey: $DEPLOY_PUBKEY"

# ---- Balance check ----
say "Checking balance..."
BALANCE=$(solana balance --lamports | awk '{print $1}')
BALANCE_SOL=$(echo "scale=4; $BALANCE / 1000000000" | bc)
ok "Balance: $BALANCE_SOL SOL"

NEEDED=$(echo "$MIN_BALANCE_SOL * 1000000000" | bc | cut -d. -f1)
if [ "$BALANCE" -lt "$NEEDED" ]; then
  if [ "$NETWORK" = "devnet" ]; then
    say "Requesting devnet airdrop..."
    solana airdrop 2 || warn "Airdrop failed (rate-limited). Try https://faucet.solana.com instead."
    sleep 3
    BALANCE=$(solana balance --lamports | awk '{print $1}')
    if [ "$BALANCE" -lt "$NEEDED" ]; then
      die "Still insufficient. Get devnet SOL from https://faucet.solana.com — paste $DEPLOY_PUBKEY"
    fi
  else
    die "Insufficient mainnet SOL. Send at least $MIN_BALANCE_SOL SOL to $DEPLOY_PUBKEY then re-run."
  fi
fi

save_state

# ---- Mainnet safety gate ----
if [ "$NETWORK" = "mainnet" ]; then
  echo ""
  warn "=========================================="
  warn "  MAINNET DEPLOY — THIS COSTS REAL MONEY"
  warn "=========================================="
  warn "Mint will be: HATE, 9 decimals, 1B supply"
  warn "Deploy wallet: $DEPLOY_PUBKEY"
  warn "Balance: $BALANCE_SOL SOL"
  echo ""
  read -p "Type 'deploy hate' to continue, anything else to abort: " confirm
  [ "$confirm" = "deploy hate" ] || die "Aborted by user."
fi

# ---- Step 1: Create mint ----
if [ -z "${MINT:-}" ]; then
  say "Creating Token-2022 mint with $DECIMALS decimals..."
  CREATE_OUT=$(spl-token --program-id "$TOKEN_2022_PROGRAM" create-token --decimals $DECIMALS 2>&1)
  MINT=$(echo "$CREATE_OUT" | grep -oE 'Address:[^ ]+|Creating token [A-Za-z0-9]+' | grep -oE '[A-Za-z0-9]{32,}' | head -1)
  [ -z "$MINT" ] && die "Could not parse mint address from output:\n$CREATE_OUT"
  ok "Mint: $MINT"
  save_state
else
  ok "Mint already created: $MINT"
fi

# ---- Step 2: Create treasury token account ----
if [ -z "${TREASURY:-}" ]; then
  say "Creating treasury token account..."
  CREATE_OUT=$(spl-token create-account "$MINT" 2>&1)
  TREASURY=$(echo "$CREATE_OUT" | grep -oE 'Creating account [A-Za-z0-9]+' | grep -oE '[A-Za-z0-9]{32,}')
  if [ -z "$TREASURY" ]; then
    # Account may already exist
    TREASURY=$(spl-token accounts | grep "$MINT" | awk '{print $1}' | head -1 || true)
  fi
  [ -z "$TREASURY" ] && die "Could not determine treasury address."
  ok "Treasury account: $TREASURY"
  save_state
else
  ok "Treasury already created: $TREASURY"
fi

# ---- Step 3: Mint supply ----
say "Checking current supply..."
CURRENT_SUPPLY=$(spl-token supply "$MINT" 2>/dev/null || echo "0")
CURRENT_INT=$(echo "$CURRENT_SUPPLY" | awk -F. '{print $1}')

if [ "$CURRENT_INT" -lt "$TOTAL_SUPPLY" ]; then
  TO_MINT=$((TOTAL_SUPPLY - CURRENT_INT))
  say "Minting $TO_MINT HATE to treasury..."
  spl-token mint "$MINT" "$TO_MINT"
  ok "Mint complete"
else
  ok "Supply already at $CURRENT_SUPPLY"
fi

# Verify
FINAL_SUPPLY=$(spl-token supply "$MINT")
say "Final supply: $FINAL_SUPPLY HATE"

# ---- Step 4: Metadata ----
if [ "${METADATA_DONE:-no}" != "yes" ]; then
  echo ""
  warn "METADATA STEP — manual prep required:"
  warn "  1. Make a 512x512 PNG logo (orange square w/ \$HATE if you don't have a real one yet)"
  warn "  2. Upload to pinata.cloud → get IPFS URL"
  warn "  3. Create metadata JSON (template in LAUNCH_PLAYBOOK.md Phase 4)"
  warn "  4. Upload JSON to Pinata → get its IPFS URL"
  echo ""
  read -p "Paste the metadata JSON URL (https://gateway.pinata.cloud/ipfs/...): " META_URL
  if [ -n "$META_URL" ]; then
    say "Initializing metadata..."
    spl-token initialize-metadata "$MINT" "HATE" "HATE" "$META_URL"
    METADATA_DONE=yes
    save_state
    ok "Metadata attached"
  else
    warn "Skipping metadata — re-run script later to add it."
  fi
else
  ok "Metadata already set"
fi

# ---- Summary ----
echo ""
echo "============================================="
echo "  DEPLOY COMPLETE — $NETWORK"
echo "============================================="
echo "  Mint:        $MINT"
echo "  Treasury:    $TREASURY"
echo "  Authority:   $DEPLOY_PUBKEY"
echo "  Supply:      $FINAL_SUPPLY HATE"
echo "============================================="
echo ""
if [ "$NETWORK" = "mainnet" ]; then
  echo "NEXT STEPS (manual, in order):"
  echo "  1. Verify on solscan: https://solscan.io/token/$MINT"
  echo "  2. Set up Squads multisig at https://squads.so"
  echo "  3. Transfer 250,000,000 HATE to multisig:"
  echo "     spl-token transfer $MINT 250000000 <SQUAD_ADDRESS> --fund-recipient --allow-unfunded-recipient"
  echo "  4. RENOUNCE mint authority (irreversible — supply locked forever):"
  echo "     spl-token authorize $MINT mint --disable"
  echo "  5. Create Meteora DLMM pool at https://app.meteora.ag/dlmm/create"
  echo "  6. Send addresses to claude for site update"
else
  echo "DEVNET COMPLETE. To deploy mainnet:"
  echo "  bash deploy.sh mainnet"
fi
echo ""
echo "State saved to: $STATE_FILE"
echo "Public keys are safe to share. Keep keypair file private."
